/**
 * Created by GSN on 8/20/2015.
 */

var MAX_NUMBER_PLAYER =4;
var NUMBER_SLOT_IN_BOARD = 40;
var NUMBER_PIECE_PER_PLAYER = 2;
var NUMBER_HOME_SLOT = 3;
var NUMBER_DES_SLOT = 4;
//var PLAYER_HOME_DISTANCE = (NUMBER_SLOT_IN_BOARD / MAX_NUMBER_PLAYER);
var MAX_NUMBER_CONT_ROLL = 3;

