system ParticleSystem1
{
    technique 
    {
        visual_particle_quota                   1
        emitted_emitter_quota                   2
        material                                golden
        default_particle_width                  20
        default_particle_height                 20
        default_particle_depth                  20
        renderer                                Entity
        {
            mesh_name                           starRing.mesh
        }
        emitter                                 Point 
        {
            emission_rate                       1
            time_to_live                        1
            direction                           0 0 0
            force_emission                      true
        }
        affector                                Colour Affector1
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.684783  1 1 1 1
            time_colour                         1    1 1 1 0
        }
        affector                                Scale 
        {
            xyz_scale                           30
        }
        affector                                Vortex Affector67
        {
            rotation_axis                       0 1 0
        }
    }
}
